# Plateforme iOS minimale
platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = '1'

target 'Runner' do
  use_frameworks!
  use_modular_headers!
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
