# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = '1'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # NDI doesn't have an official public pod. It is typically added manually as a framework.
  # This Podfile prepares the environment for standard Flutter plugins.
  
  # Standard Flutter pods are added automatically by Flutter's script.
  # But here I'll provide the script link just in case.
  # script_phase :name => 'Flutter Build', :script => 'sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # NDI might require specific build settings (like Bitcode disabled)
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
